# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "radeon" "amdgpu" ];

  fileSystems."/" =
    { device = "/dev/disk/by-partlabel/ROOT";
      fsType = "btrfs";
      options = [ "subvol=root.subv" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-partlabel/ROOT";
      fsType = "btrfs";
      options = [ "subvol=nix.subv" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-partlabel/ROOT";
      fsType = "btrfs";
      options = [ "subvol=log.subv" ];
      neededForBoot = true;
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-partlabel/ROOT";
      fsType = "btrfs";
      options = [ "subvol=home.subv" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-partlabel/ROOT";
      fsType = "btrfs";
      options = [ "subvol=persist.subv" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-partlabel/BOOT";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-partlabel/SWAP"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20f0u2i12.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
