#!/bin/sh
nix --extra-experimental-features nix-command --extra-experimental-features flakes run home-manager/release-24.05 -- --extra-experimental-features nix-command --extra-experimental-features flakes switch -b backup --flake .#fm@salmon
